### ISSUE TITLE
it wont work

### ISSUE THREAD

**Issue by zenthesize** [lt-name/ChainMining#1]
it doesnt pop up in the /pluggins and cant find config file either.

**Comment by lt-name** [comment]
Which version of nk are you using?

**Comment by zenthesize** [comment]
1.1.0 does it have permissions? that might be the reason, for my server

**Comment by lt-name** [comment]
> ```
> 1.1.0 does it have permissions? that might be the reason, for my server
> ```

no, Just put it in the plugin folder, all players can use the command to open the gui

**Comment by lt-name** [comment]
My test is no problem, and bstats shows that some servers are already using this plug-in, so I think this is not a problem with the plug-in itself (Google Translate)

**Comment by zenthesize** [comment]
ill try to reinstall it, i really like the idea of plugin for thing like vein miner.

**Comment by zenthesize** [comment]
is there anything i need to install to have the menu pop up? extra plugins for this one?

**Comment by lt-name** [comment]
> is there anything i need to install to have the menu pop up? extra plugins for this one?

No, it does not require any dependencies
The menu used by this plugin is provided by nukkit (Google Translate)

**Comment by zenthesize** [comment]
hey i have no idea why it hasn't work I done everything. just simply wont pop up in commands or in my server confiq files.

**Comment by lt-name** [comment]
I cannot reproduce the problem, please provide more information such as the nk version

**Comment by zenthesize** [comment]
it also doesn't pop up the config file so I can transfer to English on my server here some photos.
![1012](https://user-images.githubusercontent.com/84170626/118437262-f1f39c00-b6a7-11eb-9a2e-cacb728a0a6e.PNG)
![10101](https://user-images.githubusercontent.com/84170626/118437263-f1f39c00-b6a7-11eb-97e6-d0ed62fcd29f.PNG)

**Comment by lt-name** [comment]
Are you sure you are using [nukkit](https://github.com/CloudburstMC/Nukkit)?

**Comment by zenthesize** [comment]
yep. its fine, i am sorry it wont work for me. is there permissions?

**Comment by lt-name** [comment]
Can you provide the log when the server starts?

**Comment by zenthesize** [comment]
its on apex hosting
![0100](https://user-images.githubusercontent.com/84170626/118893673-71f84c80-b8c8-11eb-9fa0-d7f96e83cc81.PNG)

**Comment by zenthesize** [comment]
apex allows multiple different plugins from different plugin outlits. like spigot and bukit, sponge and nukkit.

**Comment by lt-name** [comment]
I think you are not using nukkit core
nukkit is the core of Bedrock Edition, it is very different from bukkit

**Comment by zenthesize** [comment]
well, i used nukkit plugins before. plus I running a crossplay server. i don't know if that is the problem, or language I not able to get to. sorry if this pointless for me. i like the idea tho.
